client_config_backend: settings
client_config:
  client_id: 354475543939-8nd1uas8344hohc6g5sp9g0amm5rsvpi.apps.googleusercontent.com
  client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials_module.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive
